// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.2.2'
        classpath 'com.vanniktech:gradle-maven-publish-plugin:0.30.0'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}
