org.gradle.jvmargs=-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

android.useAndroidX=true
android.enableJetifier=true
android.nonTransitiveRClass=false
 
GROUP=io.github.voghdev
POM_ARTIFACT_ID=pdfviewpager
VERSION_NAME=1.2.0
 
POM_NAME=pdfviewpager
POM_PACKAGING=aar
 
POM_DESCRIPTION=Simple Android Library to render Pdf documents
POM_INCEPTION_YEAR=2021
 
POM_URL=https://github.com/voghDev/PdfViewPager
POM_SCM_URL=https://github.com/voghDev/PdfViewPager
POM_SCM_CONNECTION=scm:git@github.com:voghDev/pdfviewpager.git
POM_SCM_DEV_CONNECTION=scm:git@github.com:voghDev/pdfviewpager.git
 
POM_LICENCE_NAME=The Apache Software License, Version 2.0
POM_LICENCE_URL=http://www.apache.org/licenses/LICENSE-2.0.txt
POM_LICENCE_DIST=repo
 
POM_DEVELOPER_ID=voghDev
POM_DEVELOPER_NAME=Olmo Gallegos
POM_DEVELOPER_URL=https://github.com/voghDev